name: login
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  get: ^4.6.6
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# hien thi logo man splash khi bat app
flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/logo_vinfast_no_title.png
  image_dark: assets/images/logo_vinfast_no_title.png

  android_12:
    image: assets/images/logo_vinfast_no_title.png
    icon_background_color: "#f7f6f1"
    image_dark: assets/images/logo_vinfast_no_title.png
    icon_background_color_dark: "#272727"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/splash/
    - assets/images/onboarding/
    - assets/images/login/
    - assets/logo/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700