// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYIV7eoQx5974Y40wnZdKt7ut-WIBZJwc',
    appId: '1:962150327569:web:4f374a8c412bb627a598b0',
    messagingSenderId: '962150327569',
    projectId: 'flutter-login-app-cb497',
    authDomain: 'flutter-login-app-cb497.firebaseapp.com',
    storageBucket: 'flutter-login-app-cb497.appspot.com',
    measurementId: 'G-1J14N5HNDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwnH28fFq1GKpOZfm5oAvRXsUNKbh_F6w',
    appId: '1:962150327569:android:bf96bb8f34aec418a598b0',
    messagingSenderId: '962150327569',
    projectId: 'flutter-login-app-cb497',
    storageBucket: 'flutter-login-app-cb497.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2GSShZM2B8eTnxH9ZSilEr3ICKb10aAI',
    appId: '1:962150327569:ios:bb816072b0fba509a598b0',
    messagingSenderId: '962150327569',
    projectId: 'flutter-login-app-cb497',
    storageBucket: 'flutter-login-app-cb497.appspot.com',
    iosBundleId: 'vn.mike.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2GSShZM2B8eTnxH9ZSilEr3ICKb10aAI',
    appId: '1:962150327569:ios:bb816072b0fba509a598b0',
    messagingSenderId: '962150327569',
    projectId: 'flutter-login-app-cb497',
    storageBucket: 'flutter-login-app-cb497.appspot.com',
    iosBundleId: 'vn.mike.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYIV7eoQx5974Y40wnZdKt7ut-WIBZJwc',
    appId: '1:962150327569:web:f5be0d06806ed47fa598b0',
    messagingSenderId: '962150327569',
    projectId: 'flutter-login-app-cb497',
    authDomain: 'flutter-login-app-cb497.firebaseapp.com',
    storageBucket: 'flutter-login-app-cb497.appspot.com',
    measurementId: 'G-W6CHT4FJDL',
  );
}
